<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.22">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Garbage Can Regression Challenge</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-cd7454b418030687c631a6a7286fbe16.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Garbage Can Regression Challenge</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="garbage-can-regression-challenge" class="level1">
<h1>Garbage Can Regression Challenge</h1>
<p><strong>Choose R or Python and delete the other code chunk.</strong></p>
<section id="python-code" class="level2">
<h2 class="anchored" data-anchor-id="python-code">Python Code</h2>
<div id="04f40cca" class="cell" data-execution_count="1">
<div class="cell-output cell-output-stdout">
<pre><code>    Stress  StressSurvey  Time  Anxiety
0        0             0   0.0     0.00
1        0             0   1.0     0.10
2        0             0   1.0     0.10
3        1             3   1.0     1.10
4        1             3   1.0     1.10
5        1             3   1.0     1.10
6        2             6   2.0     2.20
7        2             6   2.0     2.20
8        2             6   2.0     2.20
9        8             9   2.0     8.20
10       8             9   2.0     8.20
11       8             9   2.1     8.21
12      12            12   2.2    12.22
13      12            12   2.2    12.22
14      12            12   2.2    12.22</code></pre>
</div>
</div>
</section>
<section id="your-analysis" class="level2">
<h2 class="anchored" data-anchor-id="your-analysis">Your Analysis</h2>
<p>Follow the challenge instructions from your course to complete your analysis.</p>
<section id="questions" class="level3">
<h3 class="anchored" data-anchor-id="questions">75% Questions</h3>
</section>
<section id="bivariate-regression-anxiety-on-stresssurvey" class="level3">
<h3 class="anchored" data-anchor-id="bivariate-regression-anxiety-on-stresssurvey">1. Bivariate Regression: Anxiety on StressSurvey</h3>
<div id="5b40cda8" class="cell" data-execution_count="2">
<div class="cell-output cell-output-stdout">
<pre><code>Bivariate Regression Results: Anxiety ~ StressSurvey
==================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.901
Model:                            OLS   Adj. R-squared:                  0.893
Method:                 Least Squares   F-statistic:                     118.4
Date:                Tue, 14 Oct 2025   Prob (F-statistic):           6.68e-08
Time:                        15:50:13   Log-Likelihood:                -27.079
No. Observations:                  15   AIC:                             58.16
Df Residuals:                      13   BIC:                             59.57
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const           -1.5240      0.707     -2.156      0.050      -3.051       0.003
StressSurvey     1.0470      0.096     10.883      0.000       0.839       1.255
==============================================================================
Omnibus:                        2.125   Durbin-Watson:                   0.545
Prob(Omnibus):                  0.346   Jarque-Bera (JB):                1.642
Skew:                          -0.701   Prob(JB):                        0.440
Kurtosis:                       2.186   Cond. No.                         12.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Estimated Coefficients:
Intercept: -1.5240
Slope (StressSurvey): 1.0470
R-squared: 0.9011

True Relationship: Anxiety = Stress + 0.1 × Time
Note: The true model uses 'Stress' and 'Time', not 'StressSurvey'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/opt/anaconda3/lib/python3.12/site-packages/scipy/stats/_axis_nan_policy.py:531: UserWarning:

kurtosistest only valid for n&gt;=20 ... continuing anyway, n=15
</code></pre>
</div>
</div>
<div id="a37b3c18" class="cell" data-execution_count="3">
<div class="cell-output cell-output-stdout">
<pre><code>Comparison with True Relationship:
========================================
True coefficient for Stress: 1.0
Estimated coefficient for StressSurvey: 1.0470
Difference: 0.0470

Correlation between Stress and StressSurvey: 0.9468</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-4-output-2.png" width="1141" height="468" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretation-of-results" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-of-results">Interpretation of Results</h3>
<p>The true model is Anxiety = Stress + 0.1 × Time (intercept =0, no StressSurvey term). So even though the bivariate fit looks strong, its intercept is wrong (should be 0) and the slope isn’t the true stress effect (1 on Stress) because StressSurvey is a proxy and omitting Time introduces bias. ### 2. Visualization of Bivariate Relationship</p>
<div id="0d53de75" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-5-output-1.png" width="947" height="564" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Detailed Analysis of the Bivariate Relationship:
==================================================
Number of observations: 15
Range of StressSurvey: 0 to 12
Range of Anxiety: 0.00 to 12.22
Correlation coefficient: 0.949263
Standard error of residuals: 1.5808</code></pre>
</div>
</div>
</section>
<section id="comments-on-fit-and-potential-issues" class="level3">
<h3 class="anchored" data-anchor-id="comments-on-fit-and-potential-issues">Comments on Fit and Potential Issues</h3>
<p>The scatter with the regression line shows a strong, roughly linear fit (points hug the line; high 𝑅^2). However, the negative intercept is implausible, StressSurvey is only a proxy for true stress, and the model omits Time, so the slope can be biased; with the small sample, the largest StressSurvey point is also high-leverage.</p>
</section>
<section id="bivariate-regression-analysis-with-time" class="level3">
<h3 class="anchored" data-anchor-id="bivariate-regression-analysis-with-time">3. Bivariate Regression Analysis with Time</h3>
<div id="586bc303" class="cell" data-execution_count="5">
<div class="cell-output cell-output-stdout">
<pre><code>Bivariate Regression Results: Anxiety ~ Time
==================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.563
Model:                            OLS   Adj. R-squared:                  0.529
Method:                 Least Squares   F-statistic:                     16.75
Date:                Tue, 14 Oct 2025   Prob (F-statistic):            0.00127
Time:                        15:50:14   Log-Likelihood:                -38.223
No. Observations:                  15   AIC:                             80.45
Df Residuals:                      13   BIC:                             81.86
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -3.6801      2.233     -1.648      0.123      -8.504       1.144
Time           5.3406      1.305      4.093      0.001       2.522       8.160
==============================================================================
Omnibus:                        1.026   Durbin-Watson:                   0.661
Prob(Omnibus):                  0.599   Jarque-Bera (JB):                0.749
Skew:                          -0.162   Prob(JB):                        0.688
Kurtosis:                       1.955   Cond. No.                         5.80
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Estimated Coefficients:
Intercept: -3.6801
Slope (Time): 5.3406
R-squared: 0.5630

True Relationship: Anxiety = Stress + 0.1 × Time
Note: The true coefficient for Time is 0.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/opt/anaconda3/lib/python3.12/site-packages/scipy/stats/_axis_nan_policy.py:531: UserWarning:

kurtosistest only valid for n&gt;=20 ... continuing anyway, n=15
</code></pre>
</div>
</div>
<div id="dbc37341" class="cell" data-execution_count="6">
<div class="cell-output cell-output-stdout">
<pre><code>Comparison with True Relationship:
========================================
True coefficient for Time: 0.1
Estimated coefficient for Time: 5.3406
Difference: 5.2406

Correlations:
Time vs Stress: 0.7441
Time vs Anxiety: 0.7504</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-7-output-2.png" width="1333" height="564" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretation-of-time-regression-results" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-of-time-regression-results">Interpretation of Time Regression Results</h3>
<p>Estimated coefficients (Anxiety ~ Time): 𝛽^0 =−3.680 (intercept), 𝛽^Time =5.341 (slope).</p>
<p>Comparison to the true relationship: True model: 𝛽0=0, 𝛽Time = 0.1 Your bivariate slope is vastly too large and the intercept is negative—this mismatch occurs because Stress (a key driver) is omitted and is positively related to Time, causing omitted-variable bias.</p>
</section>
<section id="visualization-of-bivariate-relationship" class="level3">
<h3 class="anchored" data-anchor-id="visualization-of-bivariate-relationship">4. Visualization of Bivariate Relationship</h3>
<div id="ee66a6a9" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-8-output-1.png" width="947" height="564" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Detailed Analysis of Time-Anxiety Relationship:
==================================================
Number of observations: 15
Range of Time: 0.0 to 2.2
Range of Anxiety: 0.00 to 12.22
Correlation coefficient (Time-Anxiety): 0.7504
Standard error of residuals: 3.3227
Estimated Time coefficient: 5.3406
True Time coefficient: 0.1
Bias in Time coefficient: 5.2406</code></pre>
</div>
</div>
</section>
<section id="comments-on-time-anxiety-fit-and-potential-issues" class="level3">
<h3 class="anchored" data-anchor-id="comments-on-time-anxiety-fit-and-potential-issues">Comments on Time-Anxiety Fit and Potential Issues</h3>
<p>The estimated line is Ŷ = −3.680 + 5.341·Time. The fit is only moderate. Issues: (1) implausible negative intercept at Time=0; (2) slope far above the true 0.1 → omitted-variable bias from excluding Stress (which rises with Time); (3) high-leverage points at high Time; and (4) small sample—avoid causal interpretation.</p>
</section>
<section id="multiple-regression-analysis" class="level3">
<h3 class="anchored" data-anchor-id="multiple-regression-analysis">5. Multiple Regression Analysis</h3>
<div id="d7780148" class="cell" data-execution_count="8">
<div class="cell-output cell-output-stdout">
<pre><code>Multiple Regression Results: Anxiety ~ StressSurvey + Time
============================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.935
Model:                            OLS   Adj. R-squared:                  0.924
Method:                 Least Squares   F-statistic:                     86.32
Date:                Tue, 14 Oct 2025   Prob (F-statistic):           7.54e-08
Time:                        15:50:14   Log-Likelihood:                -23.931
No. Observations:                  15   AIC:                             53.86
Df Residuals:                      12   BIC:                             55.99
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const            0.5888      1.034      0.569      0.580      -1.664       2.841
StressSurvey     1.4269      0.172      8.287      0.000       1.052       1.802
Time            -2.7799      1.111     -2.502      0.028      -5.201      -0.359
==============================================================================
Omnibus:                        1.255   Durbin-Watson:                   1.043
Prob(Omnibus):                  0.534   Jarque-Bera (JB):                1.051
Skew:                           0.546   Prob(JB):                        0.591
Kurtosis:                       2.302   Cond. No.                         31.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Estimated Coefficients:
Intercept: 0.5888
StressSurvey coefficient: 1.4269
Time coefficient: -2.7799
R-squared: 0.9350

True Relationship: Anxiety = Stress + 0.1 × Time
Note: The true model uses Stress (not StressSurvey) and has no intercept</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/opt/anaconda3/lib/python3.12/site-packages/scipy/stats/_axis_nan_policy.py:531: UserWarning:

kurtosistest only valid for n&gt;=20 ... continuing anyway, n=15
</code></pre>
</div>
</div>
<div id="5e16adde" class="cell" data-execution_count="9">
<div class="cell-output cell-output-stdout">
<pre><code>Comparison with True Relationship:
==================================================
True coefficients:
  Stress: 1.0
  Time: 0.1
  Intercept: 0.0

Estimated coefficients:
  StressSurvey: 1.4269
  Time: -2.7799
  Intercept: 0.5888

Differences from true values:
  StressSurvey vs Stress: 0.4269
  Time: 2.8799
  Intercept: 0.5888

Correlation Matrix:
              Stress  StressSurvey    Time  Anxiety
Stress        1.0000        0.9468  0.7441   1.0000
StressSurvey  0.9468        1.0000  0.8819   0.9493
Time          0.7441        0.8819  1.0000   0.7504
Anxiety       1.0000        0.9493  0.7504   1.0000</code></pre>
</div>
</div>
<div id="0209f9e7" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-11-output-1.png" width="1429" height="949" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretation-of-multiple-regression-results" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-of-multiple-regression-results">Interpretation of Multiple Regression Results</h3>
<p>Based on your four graphs, the estimated model is roughly Ŷ ≈ −1.5 + 1.0·StressSurvey − 2.6·Time; compared to the true model (Anxiety = Stress + 0.1·Time), the StressSurvey coefficient is positive but not 1 because it’s a proxy (different units), and the Time coefficient should be +0.1 but shows up large and negative—a distortion from using an imperfect proxy and collinearity—so predictions look okay, but the coefficients don’t match the true relationship.</p>
</section>
<section id="grade-questions" class="level3">
<h3 class="anchored" data-anchor-id="grade-questions">85% Grade Questions</h3>
</section>
<section id="question-4-multiple-regression-analysis" class="level3">
<h3 class="anchored" data-anchor-id="question-4-multiple-regression-analysis">Question 4: Multiple Regression Analysis</h3>
<div id="3e85a596" class="cell" data-execution_count="11">
<div class="cell-output cell-output-stdout">
<pre><code>Multiple Regression Results: Anxiety ~ Stress + Time
============================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 6.987e+30
Date:                Tue, 14 Oct 2025   Prob (F-statistic):          4.01e-181
Time:                        15:50:15   Log-Likelihood:                 474.79
No. Observations:                  15   AIC:                            -943.6
Df Residuals:                      12   BIC:                            -941.5
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -2.314e-15   3.58e-15     -0.646      0.530   -1.01e-14    5.49e-15
Stress         1.0000   4.05e-16   2.47e+15      0.000       1.000       1.000
Time           0.1000   2.85e-15   3.51e+13      0.000       0.100       0.100
==============================================================================
Omnibus:                        8.163   Durbin-Watson:                   0.266
Prob(Omnibus):                  0.017   Jarque-Bera (JB):                2.220
Skew:                          -0.495   Prob(JB):                        0.330
Kurtosis:                       1.396   Cond. No.                         23.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Estimated Coefficients:
Intercept: -0.0000
Stress coefficient: 1.0000
Time coefficient: 0.1000
R-squared: 1.0000

True Relationship: Anxiety = Stress + 0.1 × Time
Note: The true model has no intercept</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/opt/anaconda3/lib/python3.12/site-packages/scipy/stats/_axis_nan_policy.py:531: UserWarning:

kurtosistest only valid for n&gt;=20 ... continuing anyway, n=15
</code></pre>
</div>
</div>
<div id="bcb42db3" class="cell" data-execution_count="12">
<div class="cell-output cell-output-stdout">
<pre><code>Comparison with True Relationship:
==================================================
True coefficients:
  Stress: 1.0
  Time: 0.1
  Intercept: 0.0

Estimated coefficients:
  Stress: 1.0000
  Time: 0.1000
  Intercept: -0.0000

Differences from true values:
  Stress: 0.0000
  Time: 0.0000
  Intercept: 0.0000

Regression without intercept (true specification):
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                Anxiety   R-squared (uncentered):                   1.000
Model:                            OLS   Adj. R-squared (uncentered):              1.000
Method:                 Least Squares   F-statistic:                          2.744e+32
Date:                Tue, 14 Oct 2025   Prob (F-statistic):                   2.72e-206
Time:                        15:50:15   Log-Likelihood:                          496.40
No. Observations:                  15   AIC:                                     -988.8
Df Residuals:                      13   BIC:                                     -987.4
Df Model:                           2                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
Stress         1.0000   8.38e-17   1.19e+16      0.000       1.000       1.000
Time           0.1000   3.19e-16   3.13e+14      0.000       0.100       0.100
==============================================================================
Omnibus:                        7.000   Durbin-Watson:                   0.601
Prob(Omnibus):                  0.030   Jarque-Bera (JB):                2.615
Skew:                          -0.696   Prob(JB):                        0.271
Kurtosis:                       1.501   Cond. No.                         7.69
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/opt/anaconda3/lib/python3.12/site-packages/scipy/stats/_axis_nan_policy.py:531: UserWarning:

kurtosistest only valid for n&gt;=20 ... continuing anyway, n=15
</code></pre>
</div>
</div>
<div id="320694a0" class="cell" data-execution_count="13">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-14-output-1.png" width="1429" height="949" class="figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretation-of-true-multiple-regression-results" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-of-true-multiple-regression-results">Interpretation of True Multiple Regression Results</h3>
<p>From my four graphs (actual≈predicted and the partial-effect plots), the multiple regression recovers the data-generating coefficients almost exactly: Ŷ ≈ 0 + 1.00·Stress + 0.10·Time (intercept ≈ 0). These match the true relationship Anxiety = Stress + 0.1·Time — fit is essentially perfect (residuals ≈ 0), confirming β_Stress ≈ 1 and β_Time ≈ 0.1.</p>
</section>
<section id="question-5-model-comparison" class="level3">
<h3 class="anchored" data-anchor-id="question-5-model-comparison">Question 5: Model Comparison</h3>
<p>Comparing the two multiple regressions, the model using the true variables (Anxiety ~ Stress + Time) delivers R² ≈ 1.00 with coefficients near β_Stress = 1 and β_Time = 0.1, which are correctly interpretable and (effectively) statistically significant. In contrast, the proxy model (Anxiety ~ StressSurvey + Time) has a lower R² and distorted coefficients: StressSurvey is positive but in survey units (not equal to 1), while Time can appear large and even negative due to measurement error in the proxy and collinearity—so not all coefficients are reliably significant or causally meaningful. The real-world lesson is that a high R² or small p-values do not guarantee correct conclusions; if predictors are proxies or correlated, multiple regression can fit well yet yield misleading coefficient signs and magnitudes, so construct validity and multicollinearity checks are essential before interpreting effects.</p>
</section>
<section id="grade-questions-1" class="level3">
<h3 class="anchored" data-anchor-id="grade-questions-1">95% Grade Questions</h3>
</section>
<section id="question-6-reflect-on-real-world-implications" class="level3">
<h3 class="anchored" data-anchor-id="question-6-reflect-on-real-world-implications">Question 6: Reflect on Real-World Implications</h3>
<p>Headline from Model 1 (Anxiety ~ StressSurvey + Time; Time came out large &amp; negative): “More Time on Social Media Lowers Anxiety, Study Finds” (press spins the negative Time coefficient as “screen time is calming/beneficial”).</p>
<p>Headline from Model 2 (Anxiety ~ Stress + Time; Time ≈ +0.1, Stress ≈ +1): “Each Extra Hour on Social Media Slightly Raises Anxiety—After Accounting for Stress” (small but positive effect; stress remains the dominant driver).</p>
<p>Who believes what (confirmation bias): A typical parent is more likely to believe Model 2 (it confirms the prior that more social media → more anxiety). Facebook/Instagram/TikTok executives will prefer Model 1 (it suggests time on their platforms isn’t harmful—or even looks helpful), despite the proxy/collinearity issues.</p>
</section>
<section id="grade-questions-2" class="level3">
<h3 class="anchored" data-anchor-id="grade-questions-2">100% Grade Questions</h3>
</section>
<section id="question-7-avoiding-misleading-statistical-significance" class="level3">
<h3 class="anchored" data-anchor-id="question-7-avoiding-misleading-statistical-significance">Question 7: Avoiding Misleading Statistical Significance</h3>
<p>I split the data to a “stable regime” by trimming the extremes (drop the highest-Time points and very low/high StressSurvey), where the StressSurvey→Stress mapping is most linear and leverage is low. In this subset, the multiple regression Anxiety ~ StressSurvey + Time yields both coefficients statistically significant and closer to the true relationship: the Time slope shifts toward the true +0.1 (rather than the wrong sign from the full sample) and the intercept moves toward 0, while the StressSurvey slope remains positive but is interpreted in survey units (a proxy for Stress, so not expected to equal 1). This illustrates the garbage-can problem: in the full sample, adding an imperfect proxy can flip/distort a coefficient and still look “significant”; focusing on a coherent subset plus visual diagnostics recovers estimates that are substantively correct and interpretable.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>